export const CASL_POSTDATA = [
    {
        id: 1,
        title: '임시 공개 데이터 1',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 2,
        title: '임시 공개 데이터 2',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 3,
        title: '임시 공개 데이터 3',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 4,
        title: '임시 공개 데이터 4',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 5,
        title: '임시 공개 데이터 5',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 6,
        title: '임시 공개 데이터 6',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 7,
        title: '임시 비공개 데이터',
        userName: '작성자임',
        display: 'N',
    },
    {
        id: 8,
        title: '임시 비공개 데이터',
        userName: '작성자임',
        display: 'N',
    },
    {
        id: 9,
        title: '임시 비공개 데이터',
        userName: '작성자임',
        display: 'N',
    },
    {
        id: 10,
        title: '임시 공개 데이터 10',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 11,
        title: '임시 공개 데이터 11',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 12,
        title: '임시 공개 데이터 12',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 13,
        title: '임시 공개 데이터 13',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 14,
        title: '임시 공개 데이터 14',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 15,
        title: '임시 공개 데이터 15',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 16,
        title: '임시 공개 데이터 16',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 17,
        title: '임시 공개 데이터 17',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 18,
        title: '임시 공개 데이터 18',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 19,
        title: '임시 공개 데이터 19',
        userName: '작성자임',
        display: 'Y',
    },
    {
        id: 20,
        title: '임시 공개 데이터 20',
        userName: '작성자임',
        display: 'Y',
    },
];
