import Link from 'next/link';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import styles from './page.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

//className이나 target:"_blank" 같은 <a>의 속성을 props로 전달 가능
//href(required)는 객체로도 삽입 가능, pathname: 경로, query: 쿼리스트링 경로
//replace: 브라우저의 히스토리 스택에 새 url을 추가하지 않고 현재 스택을 대체함 (기본값 false)
//scroll: 링크 경로로 이동 시 스크롤바를 자동으로 최상단에 위치하는 옵션 (기본값 true)
//링크 이동 시 scroll이 true 상태이고 컨텐츠가 현재 뷰포트에 보이지 않을 때 (ex. margin-top을 많이 줘서 컨텐츠가 화면 밖에 아래쪽에 있을 경우) 자동으로 스크롤바가 컨텐츠가 있는 부분으로 이동함
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={inter.className}>
                <header className={styles.header}>
                    <nav className={styles.nav}>
                        <Link href="/pokemons" replace scroll={false}>
                            <button className={styles.button}>포켓몬 페이지</button>
                        </Link>
                        <Link href="/todolist">
                            <button className={styles.button}>투두리스트 페이지</button>
                        </Link>
                        <Link href="/client">
                            <button className={styles.button}>CSR 컴포넌트 페이지</button>
                        </Link>
                        <Link href="/notRoute">
                            <button className={styles.button}>뒤로가기 페이지</button>
                        </Link>
                    </nav>
                </header>
                <main>{children}</main>
            </body>
        </html>
    );
}
